using PractiZing.Base.Common;
using PractiZing.Base.Entities.ChargePaymentService;
using PractiZing.Base.Entities.PatientService;
using PractiZing.Base.Object.ChargePaymentService;
using PractiZing.Base.Object.DenialService;
using PractiZing.Base.Object.MasterServcie;
using PractiZing.Base.Object.PatientService;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;

namespace PractiZing.Base.Repositories.ChargePaymentService
{
    public interface IChargesRepository
    {
        Task<IEnumerable<ICharges>> GetById(IEnumerable<int> invoiceId, IEnumerable<int> patientCaseId, IPaymentFilterDTO filter);
        Task<IEnumerable<ICharges>> GetById(int invoiceId, int patientCaseId);
        Task<IEnumerable<ICharges>> GetByIds(IEnumerable<int> Ids);
        Task<ICharges> GetByUId(Guid UId);
        Task<IEnumerable<int>> GetByUIds(IEnumerable<string> UIds);
        Task<ICharges> GetById(int Id);
        Task<IEnumerable<ICharges>> GetView(IEnumerable<int> invoiceIds, IEnumerable<int> patientCaseId, bool IsShowOnlyClaimed);
        Task<IEnumerable<ICharges>> GetBalance(IChargePaymentBillingHistoryFilter filter);
        Task<ICharges> GetGcCodeEntry(int invoiceId);
        Task<IEnumerable<ICharges>> GetByIds(IEnumerable<IDenialManagementInsuranceTypeDTO> chargeIds, bool isSelfPayment);
        Task<IEnumerable<ICharges>> GetCharges(IEnumerable<int> chargeIds);
        Task<ICharges> Get(int chargeNo, decimal amount);
        Task<IEnumerable<ICharges>> GetNumber(IEnumerable<int> chargeNos, IEnumerable<int> patientCaseIds);
        Task<IEnumerable<IPatientChargesStatementDTO>> GetStatement(IEnumerable<int> patientCaseId, DateTime fromDate, DateTime toDate);
        Task<IEnumerable<ICharges>> GetCharges(IChargePaymentBillingHistoryFilter filter);
        Task<IEnumerable<ICharges>> Get(IEnumerable<int> invoiceIds);
        Task<IChargeBatchTabsCount> GetAll(IChargeDashboardBatchFilter filter);
        Task<bool> AddNewEntities(IEnumerable<ICharges> entities, int invoiceId, IEnumerable<IInsurancePolicy> insurancePolicies);
        Task<ICharges> AddNew(ICharges entity, IEnumerable<IInsurancePolicy> insurancePolicies);
        Task<bool> UpdateEntities(IEnumerable<ICharges> entities, int invoiceId, IEnumerable<IInsurancePolicy> insurancePolicies);
        Task<int> Update(ICharges entity, IEnumerable<IInsurancePolicy> insurancePolicies);
        Task<int> Update(ICharges entity);
        Task UpdateDueBy(IEnumerable<int> chargeIds, bool isAmountDue = false);
        Task<int> DeleteByInvoiceNo(int invoiceId);
        Task<int> Delete(Guid chargeUId);
        Task<int> DeleteGcCodeEntry(int invoiceId);
        Task<int> DeleteCharge(int invoiceId, int chargeId);
        Task DeleteChargeValidation();
        Task<IEnumerable<IValidationResult>> ThrowErrors(IEnumerable<int> chargeNoGet, IEnumerable<int> chargeNoExists);
        Task<bool> ChangeDueBy(Guid invoiceUId, Guid chargeUId, string dueBy, Guid patientCaseUId, DateTime billFromDate);
        Task<int> UpdateIsDeleted(int chargeId);
        Task<IEnumerable<ICharges>> Get(int invoiceId);
        Task<int> DeleteByChargeId(int invoiceId, int chargeId);
        Task<IEnumerable<IInvoiceDTO>> GetInvoicesFromCharges(IChargeDashboardBatchFilter filter);
        Task<IEnumerable<IInvoiceDTO>> GetInvoicesFromChargesByInvoiceUids(List<Guid> invoiceUids);
        Task<bool> RunChargeScrub(int invoiceId);
        Task<IEnumerable<ICharges>> GetChargesByPatientCaseId(IChargePaymentBillingHistoryFilter filter);
        Task<IEnumerable<IChargeViewAccessionWise>> GetChargesByAccessionNumberWise(string accessionNumber);
        Task<IEnumerable<ICharges>> GetChargeView(IEnumerable<int> invoiceIds);
        Task<DataTable> GetExcelForPatientDetailInsuranceAging(DateTime fromDate, Guid insCompanyUId);
        Task<int> UpdateWithShiftDate(ICharges entity);
        Task<int> UpdateAllowedAmount(ICharges entity);        
        Task<IEnumerable<IInvoice>> GetDataForSecondaryClaims();
        Task<IEnumerable<ICharges>> GetChargesForBulkAdjustments(List<Guid> invoiceUids);
        Task<DataTable> GetExcelForPostingPayments(IReportParameterDTO parameterObject);
        Task<ICharges> GetChargeByDosAndCptCode(int patientCaseId, string cptcode, DateTime dosDate);
        Task<ICharges> GetChargeByDosAndCptCodeAndProvider(int patientCaseId, string cptcode, DateTime dosDate, int performingProviderId);
        Task<bool> UploadExcelForReportDataForCatalystAllChargesToSFTP();
        Task<IEnumerable<ICharges>> GetChargesByPatientId(long patientId);
        Task<IEnumerable<ICharges>> GetExistsCharge(int invoiceId, int patientCaseId, short performingProviderId, string cptCode);
        Task<int> UpdateQuantityAndAmount(ICharges entity, bool isQtyUpdate = false);
        Task<IEnumerable<ICharges>> GetForChargeReference(int invoiceId);
        Task<IEnumerable<ICharges>> GetCahrges97201To05(int patientCaseId);
        Task<IEnumerable<ICharges>> Validate90791(int patientCaseId);
        Task<IEnumerable<ICharges>> GetByInvoiceId(Guid invoiceUId);
        Task<IEnumerable<ICharges>> GetAccessionForEolledUpchild(Guid invoiceUId);
        Task<IEnumerable<ICharges>> GetExistsChargeForRollUp(int invoiceId, int patientCaseId, short performingProviderId, string cptCode);
        Task<IEnumerable<ICharges>> GetRollUpCharges(IChargePaymentBillingHistoryFilter filter);
        Task<IEnumerable<ICharges>> DuplicateCharges(IChargePaymentBillingHistoryFilter filter);
        Task Throw90834ChargeError();
        Task<bool> UploadExcelForActionNoteDataDataForCatalystAllChargesToSFTP();
        Task<IEnumerable<ICharges>> GetRejectedCharges(IChargePaymentBillingHistoryFilter filter);
        Task<int> MarkAsRejected(int chargeId);
        Task<IEnumerable<IBalanceCharge>> GetChargesForAdjustment(int patientCaseId);
        Task ThrowJCodeError();
        Task<IChargesDueAmountForEMR> GetDueChargesForEMR(int patientCaseId, Guid patientCaseUId);
        Task<IEnumerable<ICharges>> GetChargesForRefreshFeeAmountWhilePolicySyncing(int patientCaseId);
        Task<int> UpdateAmountWhilePolicySyncing(ICharges entity);
        Task<bool> UpdatePatientStatementCount(IEnumerable<ICharges> list);
        Task<IEnumerable<ICharges>> GetChargesForUpdateFeeAmount(List<int> ids);
        Task<IEnumerable<IRolledUpEncounterDTO>> GetLockedCharges();
        Task<bool> UpdateIsRolledUpNotifyToEMR(IEnumerable<IRolledUpEncounterDTO> list);
        Task<bool> Check7DayLogic(int invoiceId);
        Task ThrowRecurringError();
        Task<IEnumerable<ICharges>> GetChargesNew(IChargePaymentBillingHistoryFilter filter);
        Task<IEnumerable<ICharges>> GetChargesForBulkAdjustmentsNew(List<Guid> invoiceUids);
        Task<IEnumerable<ICharges>> GetByInvoiceIdFor7DayLogic(int invoiceId);
        Task<int> UpdateDueByWhilePolicySyncing(ICharges entity);
        Task<IEnumerable<ICharges>> GetChargesForBulkAdjustmentsByChargeIds(List<int> chargeIds);
        Task<int> UpdatePerformingProviderIdForNineSeries(ICharges entity);
        Task<int> UpdateFromAI(ICharges entity);
        Task<int> Check14CountLogicForH0015(int invoiceId);
        Task<IEnumerable<ICharges>> GetAllForMakeClaims();
        Task UpdateDueByFromSelfRatherThan(int invoiceId);
        Task UpdateDueByFromSelfRatherThan_UNDO(int invoiceId);
    }
}
