using System;
using System.Collections.Generic;

namespace PractiZing.Base.Entities.ChargePaymentService
{
    public interface IChargesReportDataConsolidate
    {
        long Id { get; set; }
        int ChargeId { get; set; }
        DateTime ChargePostDate { get; set; }
        DateTime DosDate { get; set; }
        string CptCode { get; set; }
        string Description { get; set; }
        decimal? ChargeAmount { get; set; }
        decimal? Payment { get; set; }
        decimal? Adjustment { get; set; }
        decimal? DueAmount { get; set; }
        string Aging { get; set; }
        string AgingText { get; set; }
        string AdjustmentCode { get; set; }
        string Denial { get; set; }
        int InsuranceCompanyId { get; set; }
        string InsuranceCompanyName { get; set; }
        string CompanyType { get; set; }
        int PerforingProviderId { get; set; }
        string PerforingProviderName { get; set; }
        string PaymentReceived { get; set; }
        int ClaimId { get; set; }
        DateTime? ClaimSentDate { get; set; }
        string ClaimStatus { get; set; }
        int PerformingFacilityId { get; set; }
        string PerformingFacilityName { get; set; }
        DateTime CreatedDate { get; set; }
        decimal? DenialAmount { get; set; }
        string DueBy { get; set; }
        string ClaimSent { get; set; }
        string PaymentPostDate { get; set; }
        string RemitDate { get; set; }
        int InvoiceId { get; set; }
        int PatientCaseId { get; set; }
        string BillingID { get; set; }
        string FirstName { get; set; }
        string LastName { get; set; }
        DateTime? DOB { get; set; }
        int PatientId { get; set; }
        string PatientUId { get; set; }
        string InvoiceUId { get; set; }
        string PatientCaseUId { get; set; }
        string PerformingProviderUId { get; set; }
        string PatientName { get; set; }
        string AccessionNumber { get; set; }
        string AgingByPostDate { get; set; }
        string AgingByPostDateText { get; set; }
        string DBName { get; set; }
        decimal? FeeAmount { get; set; }
        string ReasonCodeDescription { get; set; }
        decimal? WriteOffAmount { get; set; }
        string WriteOffReasonCode { get; set; }
        decimal? PatientPayment { get; set; }
        decimal? COGs { get; set; }
        int BillProviderId { get; set; }
        string BillProviderName { get; set; }
        int BillFacilityId { get; set; }
        string BillFacilityName { get; set; }
        int OrderringProviderId { get; set; }
        string OrderringProviderName { get; set; }
        int SupervisingProviderId { get; set; }
        string SupervisingProviderName { get; set; }
        string POS { get; set; }
        string AuthorizationNumber { get; set; }
        string Mod1 { get; set; }
        string Mod2 { get; set; }
        string Mod3 { get; set; }
        string Mod4 { get; set; }
        string ICD1 { get; set; }
        string ICD2 { get; set; }
        string ICD3 { get; set; }
        string ICD4 { get; set; }
        int QTY { get; set; }
        int RollUpQty { get; set; }
        string RollUpAccessions { get; set; }
        string IsRollUp { get; set; }
        string Deleted { get; set; }
        string RollUpRefAccession { get; set; }
        string ReasonCode1 { get; set; }
        string ReasonCode2 { get; set; }
        string ReasonCode3 { get; set; }
        string ReasonCode4 { get; set; }
        string RemarkCode1 { get; set; }
        string RemarkCode2 { get; set; }
        string RemarkCode3 { get; set; }
        string RemarkCode4 { get; set; }
        string RemarkCodes { get; set; }
        int PrimaryInsuranceCompanyId { get; set; }
        string PrimaryPolicyNo { get; set; }
        string PrimaryPolicyHolderName { get; set; }
        string PrimaryPolicyHolderDOB { get; set; }
        string PrimaryPolicyHolderRelation { get; set; }
        string PrimaryInsuranceCompanyName { get; set; }
        string PrimaryCompanyType { get; set; }
        int SecondaryInsuranceCompanyId { get; set; }
        string SecondaryPolicyNo { get; set; }
        string SecondaryPolicyHolderName { get; set; }
        string SecondaryPolicyHolderDOB { get; set; }
        string SecondaryPolicyHolderRelation { get; set; }
        string SecondaryInsuranceCompanyName { get; set; }
        string SecondaryCompanyType { get; set; }
        DateTime? Date30 { get; set; }
        DateTime? Date60 { get; set; }
        DateTime? Date90 { get; set; }
        DateTime? Date120 { get; set; }
        string PatientPhone { get; set; }
        string PatientSSN { get; set; }
        string PerformingQualification { get; set; }
        string OrderringQualification { get; set; }
        int RefDcotorId { get; set; }
        string RefDcotorName { get; set; }
        string NoteCategoryName { get; set; }
        string ChargeNote { get; set; }
        DateTime? ChargeNoteDate { get; set; }
        string EmrBillingId { get; set; }
        bool IsBillable { get; set; }
        string NonBillableComments { get; set; }
        string PatientAccountNumber { get; set; }
        string ICNNumber { get; set; }
        string PatientAccountNumberSecondary { get; set; }
        string ICNNumberSecondary { get; set; }
        string AssignedTo { get; set; }
        string AssignedBy { get; set; }
        DateTime? AssignedDate { get; set; }
        bool InWriteOffQueue { get; set; }
        string WriteOffRequestReasonCode { get; set; }
        string WriteOffRequestReasonCodeDesc { get; set; }
        string WriteOffRequestComment { get; set; }
        string WriteOffRequestStatus { get; set; }
        DateTime WriteOffRequestDate { get; set; }
        string WriteOffRequestBy { get; set; }
        DateTime? WriteOffRequestModifiedDate { get; set; }
        bool IsRejected { get; set; }
        string RejectedPIN { get; set; }
        bool? IsSynced { get; set; }
        bool? IsMedicaidCharge { get; set; }
    }
}
