using System;
using System.Collections.Generic;

namespace PractiZing.Base.Entities.ChargePaymentService
{
    public interface IChargesReportData 
    {
        long Id { get; set; }
        Guid ChargeUId { get; set; }
        int ChargeId { get; set; }
        DateTime ChargePostDate { get; set; }
        DateTime DosDate { get; set; }
        string CptCode { get; set; }
        string Description { get; set; }
        decimal ChargeAmount { get; set; }
        decimal? Payment { get; set; }
        decimal? Adjustment { get; set; }
        string BillFacilityName { get; set; }
        decimal? DueAmount { get; set; }
        decimal? DenialAmount { get; set; }
        string Aging { get; set; }
        string AgingText { get; set; }
        string AdjustmentCode { get; set; }
        string Denial { get; set; }
        int InsuranceCompanyId { get; set; }
        string InsuranceCompanyName { get; set; }
        string CompanyType { get; set; }
        int PerforingProviderId { get; set; }
        string PerforingProviderName { get; set; }
        string PaymentReceived { get; set; }
        int? ClaimId { get; set; }
        DateTime? ClaimSentDate { get; set; }
        string ClaimStatus { get; set; }
        int? PerformingFacilityId { get; set; }
        string PerformingFacilityName { get; set; }
        DateTime CreatedDate { get; set; }
        string DueBy { get; set; }
        string ClaimSent { get; set; }
        string PaymentPostDate { get; set; }
        string RemitDate { get; set; }
        int InvoiceId { get; set; }
        int PatientCaseId { get; set; }
        int PatientId { get; set; }
        string BillingID { get; set; }
        string FirstName { get; set; }
        string LastName { get; set; }
        DateTime DOB { get; set; }
        string PatientUId { get; set; }
        string PerformingProviderUId { get; set; }
        string PatientCaseUId { get; set; }
        string InvoiceUId { get; set; }
        string PatientName { get; set; }
        string AccessionNumber { get; set; }
        string AgingByPostDate { get; set; }
        string AgingByPostDateText { get; set; }
        string ReasonCodeDescription { get; set; }
        decimal? FeeAmount { get; set; }
        decimal? WriteOffAmount { get; set; }
        decimal? PatientPayment { get; set; }
        string ReasonCode1 { get; set; }
        string ReasonCode2 { get; set; }
        string ReasonCode3 { get; set; }
        string ReasonCode4 { get; set; }
        string Deleted { get; set; }
        int? PrimaryInsuranceCompanyId { get; set; }
        string PrimaryInsuranceCompanyName { get; set; }
        DateTime? LastNoteDate { get; set; }
        string CategoryName { get; set; }
        string Mod1 { get; set; }
        string Mod2 { get; set; }
        bool? IsBillable { get; set; }
        string NonBillableComments { get; set; }
        DateTime? ChargeNoteDate { get; set; }
        string ChargeNote { get; set; }
        string NoteCategoryName { get; set; }
        string ChargeNoteDateTemp { get; set; }
        string PatientAccountNumber { get; set; }
        string ICNNumber { get; set; }
        string PatientAccountNumberSecondary { get; set; }
        string ICNNumberSecondary { get; set; }
        string AssignedTo { get; set; }
        string AssignedBy { get; set; }
        DateTime? AssignedDate { get; set; }
        string PrimaryPolicyNo { get; set; }
        string SecondaryPolicyNo { get; set; }
        bool InWriteOffQueue { get; set; }
        string WriteOffRequestReasonCode { get; set; }
        string WriteOffRequestComment { get; set; }
        string WriteOffRequestStatus { get; set; }
        DateTime WriteOffRequestDate { get; set; }
        string WriteOffRequestBy { get; set; }
        DateTime WriteOffRequestModifiedDate { get; set; }
        string WriteOffRequestReasonCodeDesc { get; set; }
        int ChargeInWriteOffId { get; set; }
        string SecondaryInsuranceCompanyName { get; set; }
        string ICD1 { get; set; }
        string ICD2 { get; set; }
        string ICD3 { get; set; }
        string ICD4 { get; set; }
        string IsRollUp { get; set; }
        DateTime? PrimarySentDate { get; set; }
        DateTime? SecondarySentDate { get; set; }
        bool IsRejected { get; set; }
        string RejectedPIN { get; set; }
        int Qty { get; set; }
        string ProviderLicence { get; set; }
        string POS { get; set; }
        int? SecondaryInsuranceCompanyId { get; set; }
        int PatientStatementCount { get; set; }
        string PerformingProfessionalAbbreviation { get; set; }
        string PrimaryPriorAuthorizationNumber { get; set; }
        string SecondaryPriorAuthorizationNumber { get; set; }
        int? ChargePrimaryCompanyId { get; set; }
        int? ChargeSecondaryCompanyId { get; set; }
        int? ChargeTertiaryCompanyId { get; set; }
        string ChargePrimaryCompanyName { get; set; }
        string ChargeSecondaryCompanyName { get; set; }
        string ChargeTertiaryCompanyName { get; set; }
        string ChargePrimaryCompanyType { get; set; }
        string ChargeSecondaryCompanyType { get; set; }
        string ChargeTertiaryCompanyType { get; set; }
        bool? IsMedicaidCharge { get; set; }
        bool ReviewNeeded { get; set; }
        string ReviewComments { get; set; }
        string RemarkCodes { get; set; }
        string Remark1Desc { get; set; }
        string Remark2Desc { get; set; }
        string Remark3Desc { get; set; }
        string Remark4Desc { get; set; }
        string Solution { get; set; }
        string PrimaryCompanyType { get; set; }
    }
}
