using System;
using System.Collections.Generic;

namespace PractiZing.Base.Entities.ChargePaymentService
{
    public interface IClaim : IStamp, IUniqueIdentifier, IPracticeDTO
    {
        int StatusOfBatch { get; set; }

        int Id { get; set; }


        short? InsLevel { get; set; }
        string InsuranceLevel { get; }
        int InsuranceCompanyId { get; set; }
        int InvoiceId { get; set; }
        short? CarrierTypeId { get; set; }
        short? CaseTypeId { get; set; }
        string CaseIdNumber { get; set; }
        short? FormTypeId { get; set; }
        short? MaxServices { get; set; }
        int PatientCaseId { get; set; }
        string PayerName { get; set; }
        DateTime ClaimDate { get; set; }
        DateTime? FromDate { get; set; }
        DateTime? ToDate { get; set; }
        int VisitNo { get; set; }
        short? Frequency { get; set; }
        double TotalBilled { get; set; }
        string ClaimToAddress1 { get; set; }
        string ClaimToAddress2 { get; set; }
        string ClaimToCity { get; set; }
        string ClaimToState { get; set; }
        string ClaimToZip { get; set; }
        short? ClaimType { get; set; }
        string InsuranceType { get; set; }
        string FillingCode { get; set; }
        int OtherInsCompanyId { get; set; }
        string OtherInsType { get; set; }
        string OtherInsFillingCode { get; set; }
        string PatientName { get; set; }
        string PatientFirstName { get; set; }
        string PatientLastName { get; set; }
        string PatientMiddleName { get; set; }
        string PatientGender { get; set; }
        string PatientAreaCode { get; set; }
        string PatientStreet { get; set; }
        string PatientCity { get; set; }
        string PatientState { get; set; }
        string PatientZip { get; set; }
        string PatientPhone { get; set; }
        DateTime? PatientDOB { get; set; }
        short? PolicyHolderRelation { get; set; }
        string PolicyNo { get; set; }
        string PolicyHolderName { get; set; }
        string PolicyHolderStreet { get; set; }
        string PolicyHolderCity { get; set; }
        string PolicyHolderState { get; set; }
        string PolicyHolderZip { get; set; }
        string PolicyHolderPhone { get; set; }
        string PolicyHolderGroupNo { get; set; }
        DateTime? PolicyHolderDOB { get; set; }
        short? PolicyHolderSex { get; set; }
        string PolicyHolderEmpl { get; set; }
        string PolicyInsurancePlanName { get; set; }
        bool HasAnotherPlan { get; set; }
        short? OtherPolicyHolderRelation { get; set; }
        string OtherPolicyHolderName { get; set; }
        string OtherPolicyNo { get; set; }
        string OtherPolicyHolderGroupNo { get; set; }
        string OtherPolicyHolderStreet { get; set; }
        string OtherPolicyHolderCity { get; set; }
        string OtherPolicyHolderState { get; set; }
        string OtherPolicyHolderZip { get; set; }
        DateTime? OtherPolicyHolderDOB { get; set; }
        short? OtherPolicyHolderSex { get; set; }
        string OtherPolicyHolderEmpl { get; set; }
        string OtherPolicyInsurancePlanName { get; set; }
        string Box10Value { get; set; }
        DateTime? PatientSignatureDate { get; set; }
        string PolicyHolderSignature { get; set; }
        string PolicyHolderAreaCode { get; set; }
        short? ReferringPhyId { get; set; }
        string ReferringPhyName { get; set; }
        string BillingDoctorIDPrefix { get; set; }
        string PhysicianIdOrAuthNo { get; set; }
        string ReferringPhysicianNpi { get; set; }
        string ReferringPhyQualifier { get; set; }
        string ReferringPhyFirstName { get; set; }
        string ReferringPhyLastName { get; set; }
        string RESERVED19 { get; set; }
        bool? ShowCPTDescripton { get; set; }
        string MedicaidResubmissionCode { get; set; }
        string OriginalReferenceNumber { get; set; }
        string PriorAuthorizationNumber { get; set; }
        bool AcceptAssignment { get; set; }
        string PhysicianSignature { get; set; }
        DateTime? SentDate { get; set; }
        string BillingFacilityId { get; set; }
        string BillingDoctorPhone { get; set; }
        string BillingDoctorName { get; set; }
        string BillingDoctorAddressLine1 { get; set; }
        string BillingDoctorAddressLine2 { get; set; }
        string BillingDoctorCity { get; set; }
        string BillingDoctorState { get; set; }
        string BillingDoctorZip { get; set; }
        string BillingDoctorFax { get; set; }
        string BillingDoctorAreaCode { get; set; }
        string BillingFacilityNPI { get; set; }
        string BillingFacilityIDQualifier { get; set; }
        string GRP { get; set; }
        short? ClearingHouseId { get; set; }
        string ShouldBePrinted { get; set; }
        string CanBeSentElectronically { get; set; }
        string Status { get; set; }
        int? ClaimBatchId { get; set; }
        int FLAGS { get; set; }
        string HoldBy { get; set; }
        DateTime? HoldDate { get; set; }
        string HoldComment { get; set; }
        string ReleaseComment { get; set; }
        string ReleaseBy { get; set; }
        DateTime? ReleaseDate { get; set; }
        short? SupervisingPhysID { get; set; }
        bool? IsAuto { get; set; }
        DateTime? CurrentIllnesDate { get; set; }
        DateTime? OtherIllnesDate { get; set; }
        DateTime? UnableToWorkFrom { get; set; }
        DateTime? UnableToWorkTo { get; set; }
        DateTime? HospitalizationFrom { get; set; }
        DateTime? HospitalizationTo { get; set; }
        string DiagnosisCodes { get; set; }
        string FederalTaxIDNumber { get; set; }
        string PerformingDoctorPhone { get; set; }
        string PerformingDoctorName { get; set; }
        string PerformingDoctorAddressLine1 { get; set; }
        string PerformingDoctorAddressLine2 { get; set; }
        string PerformingDoctorCity { get; set; }
        string PerformingDoctorState { get; set; }
        string PerformingDoctorZip { get; set; }
        string PerformingFacilityNPI { get; set; }
        string PerformingFacilityIDQualifier { get; set; }
        int Count { get; set; }
        int BatchStatus { get; set; }
        string PatientSignatureOnFile { get; set; }
        string InsuranceSignatureOnFile { get; set; }
        string FacilityId { get; set; }
        IClaimTotal ClaimTotal { get; set; }
        string BillTypeCode { get; set; }
        bool AccEmploy { get; set; }
        bool AccAuto { get; set; }
        bool AccOther { get; set; }
        string AccState { get; set; }
        string TaxonomyCode { get; set; }
        IEnumerable<ICharges> InsuranceServices { get; set; }
        IEnumerable<IInvDiagnosis> InvDiagnoses { get; set; }
        IEnumerable<IScrubError> ScrubErrors { get; set; }

        string ClearingHouse { get; set; }
        string Carrier { get; set; }
        string FormType { get; set; }
        string BillingId { get; set; }
        string AccessionNumber { get; set; }
        string CarrierType { get; set; }
        DateTime DateOfService { get; set; }
        //string ClaimStatus { get; set; }
        string PolicyHolderAddress1 { get; set; }
        string PolicyHolderAddress2 { get; set; }
        string InsuranceCompanyCode { get; set; }
        string PatientAccountNumber { get; set; }
        bool? IsCliaNumber { get; set; }
        string BillingDoctorFirstName { get; set; }
        string BillingDoctorLastName { get; set; }
        string BillingDoctorMiddleName { get; set; }
        int? PerformingDoctorId { get; set; }
        bool? IsUpdated { get; set; }
        short? Box32FacilityId { get; set; }
        string Box32FacilityAddress1 { get; set; }
        string Box32FacilityAddress2 { get; set; }
        string Box32FacilityCity { get; set; }
        string Box32FacilityState { get; set; }
        string Box32FacilityZip { get; set; }
        string ReferringPhyMI { get; set; }
        string ReferringPhySuffix { get; set; }
        bool? IsLoop2420E { get; set; }
        bool? IsLoop2420DRequired { get; set; }
        string BillingProviderFacilityName { get; set; }
        string POSCode { get; set; }
        Guid PatientUId { get; set; }
        string ReferCliaNumber { get;set;}
        string PolicyGroupNumber { get; set; }
        string PolicyGroupName { get; set; }
        bool? IsRefProviderAndRendProviderSame { get; set; }
        int? ScrubStatus { get; set; }
        string OtherCompanyCode { get; set; }
        
        string SupervisionDoctorFirstName { get; set; }
        string SupervisionDoctorLastName { get; set; }
        string SupervisionDoctorMiddleName { get; set; }        
        string SupervisionDoctorPrefix { get; set; }
        string SupervisionDoctorSuffix { get; set; }
        string SupervisionDoctorNPI { get; set; }
        bool? IsLoop2310DRequired { get; set; }

        string PerformingLocationName { get; set; }
        string PerformingLocationAddressLine1 { get; set; }
        string PerformingLocationAddressLine2 { get; set; }
        string PerformingLocationCity { get; set; }
        string PerformingLocationState { get; set; }
        string PerformingLocationZIP { get; set; }
        string PerformingLocationPhone { get; set; }

        string PerformingDoctorFirstName { get; set; }
        string PerformingDoctorLastName { get; set; }
        string PerformingDoctorMiddleName { get; set; }
        string PerformingDoctorNPI { get; set; }
        string GroupNPI { get; set; }
        short? OrderingProviderId { get; set; }
        string OrderingDoctorFirstName { get; set; }
        string OrderingDoctorLastName { get; set; }
        string OrderingDoctorMiddleName { get; set; }
        string OrderingDoctorPrefix { get; set; }
        string OrderingDoctorSuffix { get; set; }
        string OrderingDoctorNPI { get; set; }
        string PerformingProviderTaxonomy { get; set; }
        bool? IsSendAck { get; set; }
        DateTime? SendAckDate { get; set; }
        bool? IsLoop2420ARequired { get; set; }
        string PatientControlNumber { get; set; }

        
        string SecondaryPayerName { get; set; }        
        string SecondaryInsuranceCompanyCode { get; set; }        
        string SecondaryPolicyHolderStreet { get; set; }        
        string SecondaryPolicyHolderCity { get; set; }        
        string SecondaryPolicyHolderState { get; set; }        
        string SecondaryPolicyHolderZip { get; set; }        
        string SecondaryPolicyHolderName { get; set; }        
        string SecondaryPolicyNo { get; set; }        
        short? SecondaryPolicyHolderRelation { get; set; }        
        string SecondaryInsuranceType { get; set; }        
        string SecondaryFillingCode { get; set; }        
        string SecondaryPolicyHolderGroupNo { get; set; }
        string SecondaryPolicyHolderSignature { get; set; }
        string SecondaryPatientSignatureOnFile { get; set; }
        string InsuranceCompanyType { get; set; }

        int? MedicaidClearingHouseId { get; set; }
        string MedicaidPayerId { get; set; }
        string MedicaidPayerReceiverId { get; set; }
        bool? IsMedicaidAttachment { get; set; }
        string AttachmentControlNumber { get; set; }
        Int64? TransactionNumber { get; set; }
        string TransactionStatus { get; set; }
    }
}
