//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrizettoReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/", ConfigurationName="TrizettoReference.CORETransactions")]
    public interface CORETransactions
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="RealTimeTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrizettoReference.RealTimeTransactionResponse> RealTimeTransactionAsync(TrizettoReference.RealTimeTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BatchSubmitTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrizettoReference.BatchSubmitTransactionResponse> BatchSubmitTransactionAsync(TrizettoReference.BatchSubmitTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GenericBatchSubmissionTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrizettoReference.BatchSubmitTransactionResponse> GenericBatchSubmissionTransactionAsync(TrizettoReference.BatchSubmitTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BatchSubmitAckRetrievalTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrizettoReference.BatchSubmitAckRetrievalTransactionResponse> BatchSubmitAckRetrievalTransactionAsync(TrizettoReference.BatchSubmitAckRetrievalTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BatchResultsRetrievalTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrizettoReference.BatchResultsRetrievalTransactionResponse> BatchResultsRetrievalTransactionAsync(TrizettoReference.BatchResultsRetrievalTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BatchResultsAckSubmitTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrizettoReference.BatchResultsAckSubmitTransactionResponse> BatchResultsAckSubmitTransactionAsync(TrizettoReference.BatchResultsAckSubmitTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GenericBatchRetrievalTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrizettoReference.BatchResultsRetrievalTransactionResponse> GenericBatchRetrievalTransactionAsync(TrizettoReference.BatchResultsRetrievalTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GenericBatchReceiptConfirmationTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrizettoReference.BatchResultsAckSubmitTransactionResponse> GenericBatchReceiptConfirmationTransactionAsync(TrizettoReference.BatchResultsAckSubmitTransactionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeRealTimeRequest
    {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeRealTimeResponse
    {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string payloadField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealTimeTransactionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public TrizettoReference.COREEnvelopeRealTimeRequest COREEnvelopeRealTimeRequest;
        
        public RealTimeTransactionRequest()
        {
        }
        
        public RealTimeTransactionRequest(TrizettoReference.COREEnvelopeRealTimeRequest COREEnvelopeRealTimeRequest)
        {
            this.COREEnvelopeRealTimeRequest = COREEnvelopeRealTimeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealTimeTransactionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public TrizettoReference.COREEnvelopeRealTimeResponse COREEnvelopeRealTimeResponse;
        
        public RealTimeTransactionResponse()
        {
        }
        
        public RealTimeTransactionResponse(TrizettoReference.COREEnvelopeRealTimeResponse COREEnvelopeRealTimeResponse)
        {
            this.COREEnvelopeRealTimeResponse = COREEnvelopeRealTimeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeBatchSubmission
    {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private int payloadLengthField;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string checkSumField;
        
        private byte[] payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int PayloadLength
        {
            get
            {
                return this.payloadLengthField;
            }
            set
            {
                this.payloadLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CheckSum
        {
            get
            {
                return this.checkSumField;
            }
            set
            {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeBatchSubmissionResponse
    {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private int payloadLengthField;
        
        private bool payloadLengthFieldSpecified;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string checkSumField;
        
        private byte[] payloadField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int PayloadLength
        {
            get
            {
                return this.payloadLengthField;
            }
            set
            {
                this.payloadLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayloadLengthSpecified
        {
            get
            {
                return this.payloadLengthFieldSpecified;
            }
            set
            {
                this.payloadLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CheckSum
        {
            get
            {
                return this.checkSumField;
            }
            set
            {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchSubmitTransactionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public TrizettoReference.COREEnvelopeBatchSubmission COREEnvelopeBatchSubmission;
        
        public BatchSubmitTransactionRequest()
        {
        }
        
        public BatchSubmitTransactionRequest(TrizettoReference.COREEnvelopeBatchSubmission COREEnvelopeBatchSubmission)
        {
            this.COREEnvelopeBatchSubmission = COREEnvelopeBatchSubmission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchSubmitTransactionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public TrizettoReference.COREEnvelopeBatchSubmissionResponse COREEnvelopeBatchSubmissionResponse;
        
        public BatchSubmitTransactionResponse()
        {
        }
        
        public BatchSubmitTransactionResponse(TrizettoReference.COREEnvelopeBatchSubmissionResponse COREEnvelopeBatchSubmissionResponse)
        {
            this.COREEnvelopeBatchSubmissionResponse = COREEnvelopeBatchSubmissionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeBatchSubmissionAckRetrievalRequest
    {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private int payloadLengthField;
        
        private bool payloadLengthFieldSpecified;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string checkSumField;
        
        private byte[] payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int PayloadLength
        {
            get
            {
                return this.payloadLengthField;
            }
            set
            {
                this.payloadLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayloadLengthSpecified
        {
            get
            {
                return this.payloadLengthFieldSpecified;
            }
            set
            {
                this.payloadLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CheckSum
        {
            get
            {
                return this.checkSumField;
            }
            set
            {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeBatchSubmissionAckRetrievalResponse
    {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private int payloadLengthField;
        
        private bool payloadLengthFieldSpecified;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string checkSumField;
        
        private byte[] payloadField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int PayloadLength
        {
            get
            {
                return this.payloadLengthField;
            }
            set
            {
                this.payloadLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayloadLengthSpecified
        {
            get
            {
                return this.payloadLengthFieldSpecified;
            }
            set
            {
                this.payloadLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CheckSum
        {
            get
            {
                return this.checkSumField;
            }
            set
            {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchSubmitAckRetrievalTransactionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public TrizettoReference.COREEnvelopeBatchSubmissionAckRetrievalRequest COREEnvelopeBatchSubmissionAckRetrievalRequest;
        
        public BatchSubmitAckRetrievalTransactionRequest()
        {
        }
        
        public BatchSubmitAckRetrievalTransactionRequest(TrizettoReference.COREEnvelopeBatchSubmissionAckRetrievalRequest COREEnvelopeBatchSubmissionAckRetrievalRequest)
        {
            this.COREEnvelopeBatchSubmissionAckRetrievalRequest = COREEnvelopeBatchSubmissionAckRetrievalRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchSubmitAckRetrievalTransactionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public TrizettoReference.COREEnvelopeBatchSubmissionAckRetrievalResponse COREEnvelopeBatchSubmissionAckRetrievalResponse;
        
        public BatchSubmitAckRetrievalTransactionResponse()
        {
        }
        
        public BatchSubmitAckRetrievalTransactionResponse(TrizettoReference.COREEnvelopeBatchSubmissionAckRetrievalResponse COREEnvelopeBatchSubmissionAckRetrievalResponse)
        {
            this.COREEnvelopeBatchSubmissionAckRetrievalResponse = COREEnvelopeBatchSubmissionAckRetrievalResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeBatchResultsRetrievalRequest
    {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private int payloadLengthField;
        
        private bool payloadLengthFieldSpecified;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string checkSumField;
        
        private byte[] payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int PayloadLength
        {
            get
            {
                return this.payloadLengthField;
            }
            set
            {
                this.payloadLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayloadLengthSpecified
        {
            get
            {
                return this.payloadLengthFieldSpecified;
            }
            set
            {
                this.payloadLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CheckSum
        {
            get
            {
                return this.checkSumField;
            }
            set
            {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeBatchResultsRetrievalResponse
    {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private int payloadLengthField;
        
        private bool payloadLengthFieldSpecified;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string checkSumField;
        
        private byte[] payloadField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int PayloadLength
        {
            get
            {
                return this.payloadLengthField;
            }
            set
            {
                this.payloadLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayloadLengthSpecified
        {
            get
            {
                return this.payloadLengthFieldSpecified;
            }
            set
            {
                this.payloadLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CheckSum
        {
            get
            {
                return this.checkSumField;
            }
            set
            {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResultsRetrievalTransactionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public TrizettoReference.COREEnvelopeBatchResultsRetrievalRequest COREEnvelopeBatchResultsRetrievalRequest;
        
        public BatchResultsRetrievalTransactionRequest()
        {
        }
        
        public BatchResultsRetrievalTransactionRequest(TrizettoReference.COREEnvelopeBatchResultsRetrievalRequest COREEnvelopeBatchResultsRetrievalRequest)
        {
            this.COREEnvelopeBatchResultsRetrievalRequest = COREEnvelopeBatchResultsRetrievalRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResultsRetrievalTransactionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public TrizettoReference.COREEnvelopeBatchResultsRetrievalResponse COREEnvelopeBatchResultsRetrievalResponse;
        
        public BatchResultsRetrievalTransactionResponse()
        {
        }
        
        public BatchResultsRetrievalTransactionResponse(TrizettoReference.COREEnvelopeBatchResultsRetrievalResponse COREEnvelopeBatchResultsRetrievalResponse)
        {
            this.COREEnvelopeBatchResultsRetrievalResponse = COREEnvelopeBatchResultsRetrievalResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeBatchResultsAckSubmission
    {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private int payloadLengthField;
        
        private bool payloadLengthFieldSpecified;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string checkSumField;
        
        private byte[] payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int PayloadLength
        {
            get
            {
                return this.payloadLengthField;
            }
            set
            {
                this.payloadLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayloadLengthSpecified
        {
            get
            {
                return this.payloadLengthFieldSpecified;
            }
            set
            {
                this.payloadLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CheckSum
        {
            get
            {
                return this.checkSumField;
            }
            set
            {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeBatchResultsAckSubmissionResponse
    {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private int payloadLengthField;
        
        private bool payloadLengthFieldSpecified;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string checkSumField;
        
        private byte[] payloadField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int PayloadLength
        {
            get
            {
                return this.payloadLengthField;
            }
            set
            {
                this.payloadLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayloadLengthSpecified
        {
            get
            {
                return this.payloadLengthFieldSpecified;
            }
            set
            {
                this.payloadLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CheckSum
        {
            get
            {
                return this.checkSumField;
            }
            set
            {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResultsAckSubmitTransactionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public TrizettoReference.COREEnvelopeBatchResultsAckSubmission COREEnvelopeBatchResultsAckSubmission;
        
        public BatchResultsAckSubmitTransactionRequest()
        {
        }
        
        public BatchResultsAckSubmitTransactionRequest(TrizettoReference.COREEnvelopeBatchResultsAckSubmission COREEnvelopeBatchResultsAckSubmission)
        {
            this.COREEnvelopeBatchResultsAckSubmission = COREEnvelopeBatchResultsAckSubmission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResultsAckSubmitTransactionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public TrizettoReference.COREEnvelopeBatchResultsAckSubmissionResponse COREEnvelopeBatchResultsAckSubmissionResponse;
        
        public BatchResultsAckSubmitTransactionResponse()
        {
        }
        
        public BatchResultsAckSubmitTransactionResponse(TrizettoReference.COREEnvelopeBatchResultsAckSubmissionResponse COREEnvelopeBatchResultsAckSubmissionResponse)
        {
            this.COREEnvelopeBatchResultsAckSubmissionResponse = COREEnvelopeBatchResultsAckSubmissionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface CORETransactionsChannel : TrizettoReference.CORETransactions, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class CORETransactionsClient : System.ServiceModel.ClientBase<TrizettoReference.CORETransactions>, TrizettoReference.CORETransactions
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CORETransactionsClient() : 
                base(CORETransactionsClient.GetDefaultBinding(), CORETransactionsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CoreSoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CORETransactionsClient(EndpointConfiguration endpointConfiguration) : 
                base(CORETransactionsClient.GetBindingForEndpoint(endpointConfiguration), CORETransactionsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CORETransactionsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CORETransactionsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CORETransactionsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CORETransactionsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CORETransactionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrizettoReference.RealTimeTransactionResponse> TrizettoReference.CORETransactions.RealTimeTransactionAsync(TrizettoReference.RealTimeTransactionRequest request)
        {
            return base.Channel.RealTimeTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrizettoReference.RealTimeTransactionResponse> RealTimeTransactionAsync(TrizettoReference.COREEnvelopeRealTimeRequest COREEnvelopeRealTimeRequest)
        {
            TrizettoReference.RealTimeTransactionRequest inValue = new TrizettoReference.RealTimeTransactionRequest();
            inValue.COREEnvelopeRealTimeRequest = COREEnvelopeRealTimeRequest;
            return ((TrizettoReference.CORETransactions)(this)).RealTimeTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrizettoReference.BatchSubmitTransactionResponse> TrizettoReference.CORETransactions.BatchSubmitTransactionAsync(TrizettoReference.BatchSubmitTransactionRequest request)
        {
            return base.Channel.BatchSubmitTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrizettoReference.BatchSubmitTransactionResponse> BatchSubmitTransactionAsync(TrizettoReference.COREEnvelopeBatchSubmission COREEnvelopeBatchSubmission)
        {
            TrizettoReference.BatchSubmitTransactionRequest inValue = new TrizettoReference.BatchSubmitTransactionRequest();
            inValue.COREEnvelopeBatchSubmission = COREEnvelopeBatchSubmission;
            return ((TrizettoReference.CORETransactions)(this)).BatchSubmitTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrizettoReference.BatchSubmitTransactionResponse> TrizettoReference.CORETransactions.GenericBatchSubmissionTransactionAsync(TrizettoReference.BatchSubmitTransactionRequest request)
        {
            return base.Channel.GenericBatchSubmissionTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrizettoReference.BatchSubmitTransactionResponse> GenericBatchSubmissionTransactionAsync(TrizettoReference.COREEnvelopeBatchSubmission COREEnvelopeBatchSubmission)
        {
            TrizettoReference.BatchSubmitTransactionRequest inValue = new TrizettoReference.BatchSubmitTransactionRequest();
            inValue.COREEnvelopeBatchSubmission = COREEnvelopeBatchSubmission;
            return ((TrizettoReference.CORETransactions)(this)).GenericBatchSubmissionTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrizettoReference.BatchSubmitAckRetrievalTransactionResponse> TrizettoReference.CORETransactions.BatchSubmitAckRetrievalTransactionAsync(TrizettoReference.BatchSubmitAckRetrievalTransactionRequest request)
        {
            return base.Channel.BatchSubmitAckRetrievalTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrizettoReference.BatchSubmitAckRetrievalTransactionResponse> BatchSubmitAckRetrievalTransactionAsync(TrizettoReference.COREEnvelopeBatchSubmissionAckRetrievalRequest COREEnvelopeBatchSubmissionAckRetrievalRequest)
        {
            TrizettoReference.BatchSubmitAckRetrievalTransactionRequest inValue = new TrizettoReference.BatchSubmitAckRetrievalTransactionRequest();
            inValue.COREEnvelopeBatchSubmissionAckRetrievalRequest = COREEnvelopeBatchSubmissionAckRetrievalRequest;
            return ((TrizettoReference.CORETransactions)(this)).BatchSubmitAckRetrievalTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrizettoReference.BatchResultsRetrievalTransactionResponse> TrizettoReference.CORETransactions.BatchResultsRetrievalTransactionAsync(TrizettoReference.BatchResultsRetrievalTransactionRequest request)
        {
            return base.Channel.BatchResultsRetrievalTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrizettoReference.BatchResultsRetrievalTransactionResponse> BatchResultsRetrievalTransactionAsync(TrizettoReference.COREEnvelopeBatchResultsRetrievalRequest COREEnvelopeBatchResultsRetrievalRequest)
        {
            TrizettoReference.BatchResultsRetrievalTransactionRequest inValue = new TrizettoReference.BatchResultsRetrievalTransactionRequest();
            inValue.COREEnvelopeBatchResultsRetrievalRequest = COREEnvelopeBatchResultsRetrievalRequest;
            return ((TrizettoReference.CORETransactions)(this)).BatchResultsRetrievalTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrizettoReference.BatchResultsAckSubmitTransactionResponse> TrizettoReference.CORETransactions.BatchResultsAckSubmitTransactionAsync(TrizettoReference.BatchResultsAckSubmitTransactionRequest request)
        {
            return base.Channel.BatchResultsAckSubmitTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrizettoReference.BatchResultsAckSubmitTransactionResponse> BatchResultsAckSubmitTransactionAsync(TrizettoReference.COREEnvelopeBatchResultsAckSubmission COREEnvelopeBatchResultsAckSubmission)
        {
            TrizettoReference.BatchResultsAckSubmitTransactionRequest inValue = new TrizettoReference.BatchResultsAckSubmitTransactionRequest();
            inValue.COREEnvelopeBatchResultsAckSubmission = COREEnvelopeBatchResultsAckSubmission;
            return ((TrizettoReference.CORETransactions)(this)).BatchResultsAckSubmitTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrizettoReference.BatchResultsRetrievalTransactionResponse> TrizettoReference.CORETransactions.GenericBatchRetrievalTransactionAsync(TrizettoReference.BatchResultsRetrievalTransactionRequest request)
        {
            return base.Channel.GenericBatchRetrievalTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrizettoReference.BatchResultsRetrievalTransactionResponse> GenericBatchRetrievalTransactionAsync(TrizettoReference.COREEnvelopeBatchResultsRetrievalRequest COREEnvelopeBatchResultsRetrievalRequest)
        {
            TrizettoReference.BatchResultsRetrievalTransactionRequest inValue = new TrizettoReference.BatchResultsRetrievalTransactionRequest();
            inValue.COREEnvelopeBatchResultsRetrievalRequest = COREEnvelopeBatchResultsRetrievalRequest;
            return ((TrizettoReference.CORETransactions)(this)).GenericBatchRetrievalTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrizettoReference.BatchResultsAckSubmitTransactionResponse> TrizettoReference.CORETransactions.GenericBatchReceiptConfirmationTransactionAsync(TrizettoReference.BatchResultsAckSubmitTransactionRequest request)
        {
            return base.Channel.GenericBatchReceiptConfirmationTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrizettoReference.BatchResultsAckSubmitTransactionResponse> GenericBatchReceiptConfirmationTransactionAsync(TrizettoReference.COREEnvelopeBatchResultsAckSubmission COREEnvelopeBatchResultsAckSubmission)
        {
            TrizettoReference.BatchResultsAckSubmitTransactionRequest inValue = new TrizettoReference.BatchResultsAckSubmitTransactionRequest();
            inValue.COREEnvelopeBatchResultsAckSubmission = COREEnvelopeBatchResultsAckSubmission;
            return ((TrizettoReference.CORETransactions)(this)).GenericBatchReceiptConfirmationTransactionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CoreSoapPort))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();

                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CoreSoapPort))
            {
                return new System.ServiceModel.EndpointAddress("https://api.gatewayedi.com/v2/CORE_CAQH/soap/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CORETransactionsClient.GetBindingForEndpoint(EndpointConfiguration.CoreSoapPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CORETransactionsClient.GetEndpointAddress(EndpointConfiguration.CoreSoapPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CoreSoapPort,
        }
    }
}
